### PR TITLE
fix(rule): fix handling of CodeBlock in ListItem

### LINKED ISSUE #2: Complains about file names in text
Text:

```md
# Anatomy of a Package

A minimal npm package should contain metadata in a _package.json_ file and an associated source file (usually _index.js_). In practice, packages contain more than that and you will have at least a license file and the source in various formats.
```

Result:

```
   3:61   ✓ error  Heading: Follow the standard capitalization rules for American English.
See https://owl.english.purdue.edu/owl/resource/592/01/  en-capitalization
   3:118  ✓ error  Heading: Follow the standard capitalization rules for American English.
See https://owl.english.purdue.edu/owl/resource/592/01/  en-capitalization
```

Not sure it’s a bug or a feature ;-)

### LINKED ISSUE #4: Error `Cannot read property '0' of undefined` when a code block starts with blank spaces
I am getting the following error when using this rule:

```text
✖ Error
Cannot read property '0' of undefined
at /Users/amimas/git-repo/docs/references.md

✖ Stack trace
TypeError: Cannot read property '0' of undefined
at /Users/amimas/git-repo/docs/references.md
    at new SourceCode (/Users/amimas/git-repo/website/node_modules/sentence-splitter/lib/parser/SourceCode.js:28:41)
    at new SplitParser (/Users/amimas/git-repo/website/node_modules/sentence-splitter/lib/sentence-splitter.js:31:23)
    at splitAST (/Users/amimas/git-repo/website/node_modules/sentence-splitter/lib/sentence-splitter.js:154:23)
    at checkNode (/Users/amimas/git-repo/website/node_modules/textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization.js:63:25)
    at /Users/amimas/git-repo/website/node_modules/textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization.js:157:13
    at Array.forEach (<anonymous>)
    at /Users/amimas/git-repo/website/node_modules/textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization.js:156:23
    at /Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/promise-event-emitter.js:26:36
    at Array.forEach (<anonymous>)
    at RuleTypeEmitter.PromiseEventEmitter.emit (/Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/promise-event-emitter.js:25:38)
    at Controller.enter (/Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/textlint-core-task.js:129:51)
    at Controller.__execute (/Users/amimas/git-repo/website/node_modules/@textlint/ast-traverse/lib/ast-traverse/src/index.js:45:31)
    at Controller.traverse (/Users/amimas/git-repo/website/node_modules/@textlint/ast-traverse/lib/ast-traverse/src/index.js:116:28)
    at TextLintCoreTask.startTraverser (/Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/textlint-core-task.js:124:28)
    at TextLintCoreTask.start (/Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/linter-task.js:34:14)
    at /Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/task-runner.js:26:18
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I was able to narrow down the root cause to the formatting of a particular markdown file. If I have the following content, textlint fails to run with this particular rule being enabled. If I don't use this rule, textlint runs successfully with all other rules configured.

Below is a sample of markdown file content where this rule breaks. Notice that the code block does not start at the beginning of the line.

image

The reason for the code block to not start at the beginning of the line is because it is rendered by markdown parsers like this, where it properly appears as part of a list item.

image

If I remove the blank lines at the beginning of the code block in the markdown, it gets rendered like this. It does not look properly aligned. Furthermore, I have other rules enabled that will now complain that the last list item should be `1` instead of `3` because it appears as a completely separate list.

image

If I have a regular paragraph instead of the code block which also starts with blank spaces within the list items, there's no problem. It works perfectly fine. Looks like the issue happens only when code block is used in this manner.

Not sure if this is a complicated bug or not.

### PR DESCRIPTION
**Pull request by azu**
fix #4

### CODE REVIEW

File: src/textlint-rule-en-capitalization.js [hunk 1]
```diff
@@ -145,9 +150,15 @@ const report = (context, options = {}) => {
             if (!allowLists) {
                 return;
             }
-            node.children.forEach(paragraph => {
+            node.children.forEach(blockNode => {
+                // Ignore other block node
+                // CodeBlock is a part of block node
+                // https://github.com/textlint-rule/textlint-rule-en-capitalization/issues/4
+                if (blockNode.type !== Syntax.Paragraph) {
```
Comment (azu) [inline src/textlint-rule-en-capitalization.js:157]: https://github.com/textlint-rule/textlint-rule-en-capitalization/issues/4

`blockNode` includes `CodeBlock` node.
